# Render 配置文件
services:
  - type: web
    name: yi-jing-project
    env: node
    buildCommand: cd web/src/main/back-end-JavaScript && npm install
    startCommand: cd web/src/main/back-end-JavaScript && npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    buildFilter:
      paths:
        - web/src/main/back-end-JavaScript/**/*
    # 安装Chrome依赖
    preDeployCommand: apt-get update && apt-get install -y chromium-browser fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends